// Build a self-contained HTML report from selected conversation turns. Chart
// traces come from the in-memory dataRegistry; if the user has reloaded since
// the data event fired, the chart shows a placeholder. Markdown is rendered
// via the same react-markdown + remark-gfm pipeline the live UI uses
// (renderToStaticMarkup) so the exported output never drifts from on-screen.
// Plotly is loaded from the CDN at view time to keep the file emailable
// (~tens of KB) instead of inlining the ~3.5MB bundle.
//
// Two entry points: downloadReport() saves a .html file; printReport() opens
// the same document in a new tab and triggers the browser print dialog, which
// is the dependency-free way to produce a PDF (Save as PDF).

import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { renderToStaticMarkup } from 'react-dom/server'
import type { Turn } from '../state/conversationStore'
import type {
  ChartBlock,
  MarkdownBlock,
  MetricBlock,
  RenderBlock,
  TableBlock,
  TimelineBlock,
} from '../types/blocks'
import { dataRegistry } from '../data/registry'

// The cartesian bundle covers scatter / bar / heatmap / histogram / box / pie
// / table — everything this template's agent emits. 1.3MB vs the 4.4MB full
// bundle, and it matches the plotly.js-cartesian-dist-min the live app uses.
const PLOTLY_CDN = 'https://cdn.plot.ly/plotly-cartesian-2.35.2.min.js'

export type ExportInputs = {
  title: string
  turns: Turn[]
  exportedAt?: Date
}

export function buildReportHtml({ title, turns, exportedAt = new Date() }: ExportInputs): string {
  const plotlyInits: string[] = []
  let chartCounter = 0

  const sections = turns
    .map((turn) => renderTurn(turn, () => `chart-${++chartCounter}`, plotlyInits))
    .join('\n')

  const dateStr = exportedAt.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })

  const turnNoun = turns.length === 1 ? 'turn' : 'turns'
  const plotlyScript = plotlyInits.length
    ? `<script>document.addEventListener('DOMContentLoaded', function () {\n${plotlyInits.join('\n')}\n});</script>`
    : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Report — ${esc(title)}</title>
<style>${CSS}</style>
${plotlyInits.length ? `<script src="${PLOTLY_CDN}" charset="utf-8"></script>` : ''}
</head>
<body>
<header>
  <h1>${esc(title)}</h1>
  <p class="meta">Exported ${esc(dateStr)} · ${turns.length} ${turnNoun}</p>
</header>
<main>
${sections}
</main>
<footer>
  Generated by Agent Starter
</footer>
${plotlyScript}
</body>
</html>`
}

export function downloadReport(inputs: ExportInputs): void {
  const html = buildReportHtml(inputs)
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filenameFor(inputs.title, inputs.exportedAt ?? new Date())
  document.body.appendChild(a)
  a.click()
  a.remove()
  // Revoke after the click event has been processed. setTimeout 0 is enough.
  setTimeout(() => URL.revokeObjectURL(url), 0)
}

// Open the report in a new tab and trigger the print dialog, where the user
// can pick "Save as PDF". We wait for load (so the CDN Plotly script and chart
// inits have run) before printing; the small extra delay lets Plotly lay the
// charts out so they appear in the PDF.
export function printReport(inputs: ExportInputs): void {
  const html = buildReportHtml(inputs)
  const w = window.open('', '_blank')
  if (!w) {
    // Popup blocked — fall back to a normal download so the user isn't stuck.
    downloadReport(inputs)
    return
  }
  w.document.open()
  w.document.write(html)
  w.document.close()
  const triggerPrint = () => setTimeout(() => w.print(), 400)
  if (w.document.readyState === 'complete') triggerPrint()
  else w.addEventListener('load', triggerPrint)
}

function filenameFor(title: string, date: Date): string {
  const slug =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'conversation'
  const d = date.toISOString().slice(0, 10) // YYYY-MM-DD
  return `agent-starter-report-${slug}-${d}.html`
}

function renderTurn(turn: Turn, newChartId: () => string, plotlyInits: string[]): string {
  const blocks = turn.blocks.map((b) => renderBlock(b, newChartId, plotlyInits)).join('\n')
  return `<section class="turn">
  <h2 class="prompt-h">Prompt</h2>
  <div class="prompt">${esc(turn.prompt)}</div>
  <div class="blocks">${blocks || '<div class="block-unknown">[no rendered output for this turn]</div>'}</div>
</section>`
}

function renderBlock(
  block: RenderBlock,
  newChartId: () => string,
  plotlyInits: string[],
): string {
  switch (block.type) {
    case 'markdown':
      return renderMarkdown(block)
    case 'chart':
      return renderChart(block, newChartId, plotlyInits)
    case 'table':
      return renderTable(block)
    case 'metric':
      return renderMetric(block)
    case 'timeline':
      return renderTimeline(block)
    default:
      // Exhaustiveness — TS narrows block to never. If someone adds a new
      // block type and forgets to handle it here, fall back to a noisy stub
      // so the gap is visible in the exported document.
      return `<div class="block-unknown">[unsupported block]</div>`
  }
}

function renderMarkdown(block: MarkdownBlock): string {
  // react-markdown returns sanitized HTML by default (no raw <script>),
  // so it's safe to drop the rendered markup straight into the document.
  const inner = renderToStaticMarkup(
    <ReactMarkdown remarkPlugins={[remarkGfm]}>{block.content}</ReactMarkdown>,
  )
  return `<div class="md">${inner}</div>`
}

function renderChart(
  block: ChartBlock,
  newChartId: () => string,
  plotlyInits: string[],
): string {
  const id = newChartId()
  const ref = block.dataRef
  const traces = ref ? (dataRegistry.get(ref) as unknown) : undefined

  const titleHtml = block.title ? `<div class="chart-title">${esc(block.title)}</div>` : ''

  if (!traces || !Array.isArray(traces) || traces.length === 0) {
    return `${titleHtml}<div class="chart-unavailable">Chart data unavailable for this turn (cache cleared since the run). Re-run the prompt to repopulate.</div>`
  }

  const userLayout = (block.spec?.layout as Record<string, unknown>) ?? {}
  const layout = {
    autosize: true,
    margin: { l: 56, r: 16, t: 16, b: 44 },
    paper_bgcolor: '#ffffff',
    plot_bgcolor: '#ffffff',
    font: { size: 11, color: '#1a1a1a' },
    xaxis: {
      gridcolor: '#eeeeee',
      zerolinecolor: '#dddddd',
      ...((userLayout.xaxis as object) ?? {}),
    },
    yaxis: {
      gridcolor: '#eeeeee',
      zerolinecolor: '#dddddd',
      ...((userLayout.yaxis as object) ?? {}),
    },
    legend: { bgcolor: 'rgba(0,0,0,0)', orientation: 'h', y: -0.2 },
    ...userLayout,
  }

  plotlyInits.push(
    `  Plotly.newPlot(${JSON.stringify(id)}, ${safeJson(traces)}, ${safeJson(layout)}, {displaylogo: false, responsive: true});`,
  )

  return `${titleHtml}<div id="${esc(id)}" class="chart-container"></div>`
}

function renderTable(block: TableBlock): string {
  const head = `<tr>${block.columns.map((c) => `<th>${esc(c)}</th>`).join('')}</tr>`
  const body = block.rows
    .map((r) => `<tr>${r.map((cell) => `<td>${esc(formatCell(cell))}</td>`).join('')}</tr>`)
    .join('\n')
  const title = block.title ? `<div class="block-title">${esc(block.title)}</div>` : ''
  return `${title}<table><thead>${head}</thead><tbody>${body}</tbody></table>`
}

function renderMetric(block: MetricBlock): string {
  const trendGlyph =
    block.trend === 'up' ? ' ▲' : block.trend === 'down' ? ' ▼' : block.trend === 'flat' ? ' •' : ''
  const trendClass = block.trend ? ` metric-trend-${block.trend}` : ''
  return `<div class="metric-card">
    <div class="label">${esc(block.label)}</div>
    <div class="value">${esc(formatCell(block.value))}${
      block.unit ? `<span class="unit">${esc(block.unit)}</span>` : ''
    }<span class="trend${esc(trendClass)}">${esc(trendGlyph)}</span></div>
  </div>`
}

function renderTimeline(block: TimelineBlock): string {
  const items = block.events
    .map((e) => {
      const sev = e.severity ?? 'info'
      return `<li class="${esc(sev)}"><span class="ts">${esc(e.ts)}</span>${esc(e.label)}</li>`
    })
    .join('\n')
  const title = block.title ? `<div class="block-title">${esc(block.title)}</div>` : ''
  return `${title}<ul class="timeline">${items}</ul>`
}

function esc(value: unknown): string {
  if (value == null) return ''
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function formatCell(value: unknown): string {
  if (value == null) return ''
  if (typeof value === 'number') {
    if (Number.isInteger(value)) return value.toString()
    return value.toLocaleString(undefined, { maximumFractionDigits: 3 })
  }
  if (typeof value === 'object') return JSON.stringify(value)
  return String(value)
}

// Encode plotly trace/layout data so the result is safe to inline in a
// <script>. JSON.stringify alone leaves "</script>" unencoded, which would
// terminate the script tag if it appeared in a label.
function safeJson(value: unknown): string {
  return JSON.stringify(value)
    .replace(/<\/script/gi, '<\\/script')
    .replace(/<!--/g, '<\\!--')
}

const CSS = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
         line-height: 1.6; color: #1a1a1a; background: #fafafa;
         max-width: 980px; margin: 2rem auto; padding: 0 1.5rem; }
  header { border-bottom: 1px solid #e0e0e0; padding-bottom: 1.2rem; margin-bottom: 2rem; }
  header h1 { margin: 0 0 0.4rem; font-size: 1.6rem; font-weight: 600; }
  header .meta { color: #666; font-size: 0.85rem; margin: 0; }
  section.turn { margin-bottom: 2.4rem; padding-bottom: 2rem; border-bottom: 1px solid #eee; }
  section.turn:last-child { border: 0; }
  h2.prompt-h { margin: 0 0 0.5rem; font-size: 0.72rem; font-weight: 600; color: #888;
                text-transform: uppercase; letter-spacing: 0.6px; }
  .prompt { background: #f3f3f3; border-left: 3px solid #4a8a5c; padding: 0.75rem 1rem;
            border-radius: 4px; margin-bottom: 1.2rem; font-size: 0.92rem; white-space: pre-wrap;
            font-family: inherit; }
  .blocks > * + * { margin-top: 1.2rem; }
  .block-title { font-size: 0.78rem; font-weight: 600; color: #555; margin-bottom: 0.35rem;
                 text-transform: uppercase; letter-spacing: 0.4px; }
  .md p { margin: 0 0 0.9rem; }
  .md p:last-child { margin-bottom: 0; }
  .md h1, .md h2, .md h3 { margin: 1.2rem 0 0.5rem; font-weight: 600; }
  .md h1 { font-size: 1.25rem; }
  .md h2 { font-size: 1.1rem; }
  .md h3 { font-size: 0.98rem; }
  .md ul, .md ol { margin: 0.4rem 0 0.9rem; padding-left: 1.6rem; }
  .md li { margin-bottom: 0.25rem; }
  .md strong { font-weight: 600; }
  .md code { font-family: "JetBrains Mono", "SF Mono", ui-monospace, monospace; font-size: 0.84em;
             background: #efefef; padding: 1px 5px; border-radius: 3px; }
  .md pre { background: #2b2b2b; color: #f5f5f5; padding: 0.8rem 1rem; border-radius: 6px;
            overflow-x: auto; font-size: 0.84rem; }
  .md pre code { background: transparent; padding: 0; }
  .md blockquote { border-left: 3px solid #ccc; padding-left: 0.9rem; color: #555; margin: 0.6rem 0; }
  table { border-collapse: collapse; width: 100%; font-size: 0.88rem; margin: 0.4rem 0; }
  table th, table td { padding: 0.5rem 0.7rem; border-bottom: 1px solid #ececec; text-align: left;
                       vertical-align: top; }
  table th { font-weight: 600; background: #f5f5f5; color: #333; }
  table tr:nth-child(2n) td { background: #fbfbfb; }
  .metric-card { display: inline-block; padding: 0.7rem 1.1rem; background: #fff;
                 border: 1px solid #e2e2e2; border-radius: 6px; margin: 0 0.6rem 0.6rem 0;
                 min-width: 140px; vertical-align: top; }
  .metric-card .label { font-size: 0.7rem; color: #777; text-transform: uppercase; letter-spacing: 0.4px;
                        margin-bottom: 0.3rem; }
  .metric-card .value { font-size: 1.35rem; font-weight: 600; color: #111; line-height: 1.2; }
  .metric-card .unit { font-size: 0.8rem; color: #666; margin-left: 0.2rem; font-weight: 500; }
  .metric-card .trend { font-size: 0.85rem; margin-left: 0.3rem; color: #888; }
  .metric-trend-up { color: #2c9f4b; }
  .metric-trend-down { color: #c0392b; }
  .timeline { list-style: none; padding: 0; margin: 0; border-left: 2px solid #e2e2e2; padding-left: 1rem; }
  .timeline li { position: relative; padding: 0.4rem 0 0.4rem 0.6rem; }
  .timeline li::before { content: ''; position: absolute; left: -1.42rem; top: 0.85rem;
                         width: 9px; height: 9px; border-radius: 50%; background: #9aa; border: 2px solid #fff; }
  .timeline li.warn::before { background: #f39c12; }
  .timeline li.error::before { background: #e74c3c; }
  .timeline .ts { font-family: "JetBrains Mono", "SF Mono", monospace; font-size: 0.74rem;
                  color: #888; display: block; margin-bottom: 0.1rem; }
  .chart-container { width: 100%; min-height: 380px; background: #fff; border: 1px solid #eaeaea;
                     border-radius: 6px; padding: 8px; }
  .chart-title { font-size: 0.78rem; font-weight: 600; color: #555; margin-bottom: 0.35rem;
                 text-transform: uppercase; letter-spacing: 0.4px; }
  .chart-unavailable { padding: 2rem 1rem; text-align: center; color: #999; font-style: italic;
                       background: #f5f5f5; border-radius: 6px; font-size: 0.88rem; }
  .block-unknown { color: #999; font-style: italic; }
  footer { margin-top: 3rem; padding-top: 1.2rem; border-top: 1px solid #e0e0e0;
           color: #999; font-size: 0.78rem; text-align: center; line-height: 1.5; }
  @media print {
    body { background: #fff; max-width: none; }
    /* A turn is usually taller than a page; "avoid" would push the whole
       section to the next page and strand the header alone on page 1. Let
       turns flow across pages, but keep atomic blocks from splitting. */
    section.turn { break-inside: auto; page-break-inside: auto; }
    .metric-card, .chart-container, table, .timeline, .md pre {
      break-inside: avoid; page-break-inside: avoid;
    }
    h2.prompt-h, .block-title, .chart-title { break-after: avoid; page-break-after: avoid; }
  }
`
